### ISSUE TITLE
just a small typo  in models.json

### ISSUE THREAD

**Issue by thesimpleone** [nomic-ai/gpt4all.io#13]
Found a small typo in [https://gpt4all.io/models/models.json](https://gpt4all.io/models/models.json)

commericially != commercially

```
    "md5sum": "1cfa4958f489f0a0d1ffdf6b37322809",
    "filename": "ggml-mpt-7b-instruct.bin",
    "filesize": "4854401028",
    "requires": "2.4.1",
    "description": "A commericially licensable instruct model based on MPT and trained by Mosaic ML."

```
Ln:86 Col:36 Sel:13|1

Thanks for all the amazing work y'all do!

**Comment by AndriyMulyar** [comment]
descriptions have been changed.
